image:
  repository: vothinhuydt/jenkins-abcde
  tag: lst
  pullPolicy: IfNotPresent

persistence:
    enabled: true
    existingClaim: jenkins-pvc

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClassName: ""      
  accessMode: ReadWriteOnce
  size: 10Gi

nodeSelector: {}
tolerations: []
affinity: {}


controller:
  ingress:
    enabled: true
    hosts:
      - jenkins.txuapp.com

